/*CREATING TABLE TO HOLD PLAYER RECORDS*/
CREATE TABLE PLAYER (
  PLAYERID INT PRIMARY KEY NOT NULL,
  PLAYERNAME VARCHAR(32) NOT NULL,
  HUMANTEST BOOLEAN NOT NULL
);

/*CREATING TABLE TO HOLD GAME RECORDS FOR EACH GAME*/
CREATE TABLE GAMEPLAY (
  GAMEID INT PRIMARY KEY NOT NULL,
  NO_DRAWS INT NOT NULL,
  WINNER INT NOT NULL,
  TOTAL_ROUNDS INT NOT NULL
);

/*CREATING TABLE TO HOLD RECORDS FOR ROUND WINNING RECORDS FOR EACH PLAYER AND GAME*/
CREATE TABLE ROUNDS (
  GAMEID INT NOT NULL,
  PLAYERID INT NOT NULL,
  ROUNDS INT NOT NULL,
  PRIMARY KEY (GAMEID, PLAYERID)
);

/*DEFINING NECESSARY CONSTRAINTS BASED ON PRIMARY AND FOREIGN KEYS*/
ALTER TABLE GAMEPLAY ADD FOREIGN KEY (WINNER) REFERENCES PLAYER (PLAYERID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE ROUNDS ADD FOREIGN KEY (GAMEID) REFERENCES GAMEPLAY (GAMEID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE ROUNDS ADD FOREIGN KEY (PLAYERID) REFERENCES PLAYER (PLAYERID) ON DELETE CASCADE ON UPDATE CASCADE;

/*INSERTING PLAYER RECORDS ACCORDING TO SPECIFICATIONS OF UP TO 5 PLAYERS*/ 
INSERT INTO public.player(playerid, playername, humantest)
	VALUES ('1', 'Human', 'true'),
	 ('2', 'AI_1', 'false'),
	 ('3', 'AI_2', 'false'),
	 ('4', 'AI_3', 'false'),
	 ('5', 'AI_4', 'false');
